Bhagirath Tallapragada,
btallapragada1@student.gsu.edu,
Student ID: 002575358

1. . Write a piece of code using a regular expression in Python to count how many times
the following name appears: CICERO, this regex needs to be case-sensitive. (10 points)

In [167]:
import re

openfile=open('/content/sample_data/hw_1-text.txt','r')
strings=openfile.read()

term = re.compile("CICERO")
m1 = re.findall(term, strings)
print(len(m1))

7


2. Write a regular expression in Python that finds all 6 character words found in this play.
(10 points)

In [168]:
m2 = re.findall(r'\b\w{6}\b', strings)
print(m2)
# for str in m2:
#   m_.append(str[5:])
print(len(set(m2)))

['Julius', 'Caesar', 'street', 'Second', 'answer', 'Second', 'indeed', 'mender', 'Second', 'fellow', 'Second', 'cobble', 'Second', 'meddle', 'indeed', 'danger', 'proper', 'Second', 'myself', 'indeed', 'Caesar', 'brings', 'follow', 'wheels', 'blocks', 'stones', 'things', 'hearts', 'Pompey', 'towers', 'Pompey', 'appear', 'sounds', 'shores', 'attire', 'Pompey', 'houses', 'plague', 'lowest', 'stream', 'shores', 'Exeunt', 'basest', 'vanish', 'tongue', 'images', 'matter', 'images', 'Caesar', 'vulgar', 'Caesar', 'Exeunt', 'public', 'CAESAR', 'ANTONY', 'course', 'PORTIA', 'DECIUS', 'BRUTUS', 'CICERO', 'BRUTUS', 'CAESAR', 'Caesar', 'speaks', 'CAESAR', 'CAESAR', 'course', 'ANTONY', 'Caesar', 'CAESAR', 'Forget', 'elders', 'barren', 'ANTONY', 'Caesar', 'CAESAR', 'Caesar', 'CAESAR', 'CAESAR', 'tongue', 'Caesar', 'Caesar', 'Beware', 'CAESAR', 'BRUTUS', 'beware', 'CAESAR', 'before', 'Fellow', 'throng', 'Caesar', 'CAESAR', 'Beware', 'CAESAR', 'Sennet', 'Exeunt', 'except', 'BRUTUS', 'course', 'BRUTUS',

3. Write a piece of code that uses a regular expression in Python to count how many
words are capitalized in the first letter only. (20 points)

In [170]:
m3=re.findall(r'\b[A-Z]{1}\b|[A-Z][a-z]+',strings)
print(m3)
print(len(set(m3))) #finding unique words
# this list includes single letter words like 'O', 'I' since they do not violate the given requirement

['The', 'Life', 'Death', 'Julius', 'Caesar', 'I', 'I', 'Rome', 'A', 'Enter', 'Commoners', 'Hence', 'Is', 'Being', 'Upon', 'Of', 'Speak', 'First', 'Commoner', 'Why', 'Where', 'What', 'You', 'Second', 'Commoner', 'Truly', 'I', 'But', 'Second', 'Commoner', 'A', 'I', 'I', 'What', 'Second', 'Commoner', 'Nay', 'I', 'I', 'What', 'Second', 'Commoner', 'Why', 'Thou', 'Second', 'Commoner', 'Truly', 'I', 'I', 'I', 'I', 'As', 'But', 'Why', 'Second', 'Commoner', 'Truly', 'But', 'Caesar', 'Wherefore', 'What', 'What', 'Rome', 'To', 'You', 'O', 'Rome', 'Knew', 'Pompey', 'Many', 'Have', 'To', 'Your', 'The', 'To', 'Pompey', 'Rome', 'And', 'Have', 'That', 'Tiber', 'To', 'Made', 'And', 'And', 'And', 'That', 'Pompey', 'Be', 'Run', 'Pray', 'That', 'Go', 'Assemble', 'Draw', 'Tiber', 'Into', 'Do', 'Exeunt', 'Commoners', 'See', 'They', 'Go', 'Capitol', 'This', 'I', 'If', 'May', 'You', 'Lupercal', 'It', 'Be', 'Caesar', 'I', 'And', 'So', 'These', 'Caesar', 'Will', 'Who', 'And', 'Exeunt', 'A', 'Flourish', 'Enter'

4. Write a regular expression using groups in Python that extracts all phrases that have
“son of ” and extract/output the answer in a case-insensitive way. For example, for the
following “I am the son of earth”, should find “son of earth” and extract/output “earth”.
(20 points)

In [171]:
#approach 1
m4=re.findall(r'\bson of (.[a-zA-Z]+)',strings,re.I)
print(m4)

['Rome', 'Caesar', 'Marcus', 'Marcus']


In [172]:
#approach 2
m4=[]
# string1='Than to repute himself a son of Rome'
# p3=re.search(r'\bson of (.[a-zA-Z]+)',string1)
# print(p3.group(1))
with open("/content/sample_data/hw_1-text.txt") as openfile:
    for line in openfile:
       #print(line)
       p3=re.search(r'\bson of (.[a-zA-Z]+)',line, re.I)
       if(p3!=None):
         m4.append(p3.group(1))
    print(m4)

['Rome', 'Caesar', 'Marcus', 'Marcus']


5. Plays are divided in acts, write a regular expression using groups in Python that
extracts the number of each act found in this play in a case-sensitive way. (20 points)

In [173]:
m5=[]
with open("/content/sample_data/hw_1-text.txt") as openfile:
  for line in openfile:
    p4=re.search(r'ACT (.*[A-Z]|[A-Z]+)',line)
    if(p4!=None):
      m5.append(p4.group(1))

print(m5)

['I', 'II', 'III', 'IV', 'V']


6. Write a Python function that takes the file as an input and outputs how many lines end
with: ? , that is a question mark at the end of the line. This function needs to use a
regular expression. (20 points)

In [174]:
def question_counter(file):
  m6=[]
  count=0
  with open(file) as file1:
    for line in file1:
      p5=re.search(r'.*\?$',line)
      if(p5!=None):
        m6.append(p5.group(0))
        count+=1
  #print(m6)
  return count

In [175]:
c=question_counter("/content/sample_data/hw_1-text.txt")
print(c)

215


7. Using the code from Class 04, train a Random Forest classification model for the same
two newsgroups, generate the confusion matrix, and all the same performance metrics.
(50 points)

In [176]:
from sklearn.datasets import fetch_20newsgroups

data = fetch_20newsgroups()
data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [177]:
categories = ['rec.autos','comp.graphics']
train = fetch_20newsgroups(subset='train', categories=categories)
test = fetch_20newsgroups(subset='test', categories=categories)

In [178]:
print(train.data[6])

From: ssave@ole.cdac.com (The Devil Reincarnate)
Subject: Quick question
Keywords: Removing panels.
Organization: CDAC, WA
Lines: 9

 How do you take off the driver side door panel from the inside
on an '87 Honda Prelude?  The speaker went scratchy, and I want
to access its pins.

 I see only one press button and the rest is snug fit.


 -S
 ssave@ole.cdac.com



In [179]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline

model = make_pipeline(CountVectorizer(), RandomForestClassifier())

In [180]:
model.fit(train.data, train.target)
labels = model.predict(test.data)

In [181]:
import sklearn.metrics
from sklearn.metrics import confusion_matrix
import numpy as np
mat = confusion_matrix(test.target, labels)
print(mat)

[[367  22]
 [ 34 362]]


In [182]:
print('Accuracy:', sklearn.metrics.accuracy_score(test.target,labels))
print('Precision:', sklearn.metrics.precision_score(test.target,labels))
print('Recall:', sklearn.metrics.recall_score(test.target,labels))
print('F1 Score:', sklearn.metrics.f1_score(labels, test.target, average='macro'))
print('Mean Absolute Error:', sklearn.metrics.mean_absolute_error(test.target,labels))
print('Mean Squared Error:', sklearn.metrics.mean_squared_error(test.target, labels))
print('Root Mean Squared Error:', np.sqrt(sklearn.metrics.mean_squared_error(test.target, labels)))

Accuracy: 0.9286624203821656
Precision: 0.9427083333333334
Recall: 0.9141414141414141
F1 Score: 0.9286595261278807
Mean Absolute Error: 0.07133757961783439
Mean Squared Error: 0.07133757961783439
Root Mean Squared Error: 0.26709095757407136


Bonus (15 points): Using the code from Class 04. Write a function to find the best
performing model for the TF-IDF vectorization. The requirements for this are: 1) Pass all
metrics for each model in a single dataframe (each row has a metric value, each column
is a model type). 2) Make the decision of the best model by counting which column has
the highest F1-score and accuracy

In [194]:
#creating a sample dataframe for testing

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import Perceptron
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

model1 = make_pipeline(TfidfVectorizer(), MultinomialNB())
model2 = make_pipeline(TfidfVectorizer(), Perceptron())
model3 = make_pipeline(TfidfVectorizer(), RandomForestClassifier())
model4 = make_pipeline(TfidfVectorizer(), LogisticRegression())

In [184]:
data = fetch_20newsgroups()
data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [185]:
categories = ['rec.autos','comp.graphics']
train = fetch_20newsgroups(subset='train', categories=categories)
test = fetch_20newsgroups(subset='test', categories=categories)

In [196]:
model1.fit(train.data, train.target)
model2.fit(train.data, train.target)
model3.fit(train.data, train.target)
model4.fit(train.data, train.target)
labels1 = model1.predict(test.data)
labels2 = model2.predict(test.data)
labels3 = model3.predict(test.data)
labels4 = model4.predict(test.data)

In [197]:
from sklearn.metrics import confusion_matrix
mat1 = confusion_matrix(test.target, labels1)
mat2 = confusion_matrix(test.target, labels2)
mat3 = confusion_matrix(test.target, labels3)
mat4 = confusion_matrix(test.target, labels4)

print(mat1)
print(mat2)
print(mat3)
print(mat4)

[[351  38]
 [  3 393]]
[[360  29]
 [ 11 385]]
[[362  27]
 [ 36 360]]
[[369  20]
 [ 16 380]]


In [200]:
l1=[sklearn.metrics.accuracy_score(test.target,labels1),
sklearn.metrics.precision_score(test.target,labels1),
sklearn.metrics.recall_score(test.target,labels1),
sklearn.metrics.f1_score(labels1, test.target, average='macro'),
sklearn.metrics.mean_absolute_error(test.target,labels1),
sklearn.metrics.mean_squared_error(test.target, labels1),  
np.sqrt(sklearn.metrics.mean_squared_error(test.target, labels1))
]
l2=[sklearn.metrics.accuracy_score(test.target,labels2),
sklearn.metrics.precision_score(test.target,labels2),
sklearn.metrics.recall_score(test.target,labels2),
sklearn.metrics.f1_score(labels2, test.target, average='macro'),
sklearn.metrics.mean_absolute_error(test.target,labels2),
sklearn.metrics.mean_squared_error(test.target, labels2),  
np.sqrt(sklearn.metrics.mean_squared_error(test.target, labels2))
]
l3=[sklearn.metrics.accuracy_score(test.target,labels3),
sklearn.metrics.precision_score(test.target,labels3),
sklearn.metrics.recall_score(test.target,labels3),
sklearn.metrics.f1_score(labels3, test.target, average='macro'),
sklearn.metrics.mean_absolute_error(test.target,labels3),
sklearn.metrics.mean_squared_error(test.target, labels3),  
np.sqrt(sklearn.metrics.mean_squared_error(test.target, labels3))
]
l4=[sklearn.metrics.accuracy_score(test.target,labels4),
sklearn.metrics.precision_score(test.target,labels4),
sklearn.metrics.recall_score(test.target,labels4),
sklearn.metrics.f1_score(labels4, test.target, average='macro'),
sklearn.metrics.mean_absolute_error(test.target,labels4),
sklearn.metrics.mean_squared_error(test.target, labels4),  
np.sqrt(sklearn.metrics.mean_squared_error(test.target, labels4))
]

In [201]:
print(l1)
print(l2)
print(l3)
print(l4)

[0.9477707006369427, 0.9118329466357309, 0.9924242424242424, 0.9476207603086282, 0.05222929936305733, 0.05222929936305733, 0.22853730409510245]
[0.9490445859872612, 0.9299516908212561, 0.9722222222222222, 0.9489928525016245, 0.050955414012738856, 0.050955414012738856, 0.22573305919324013]
[0.9197452229299363, 0.9302325581395349, 0.9090909090909091, 0.9197447019819189, 0.08025477707006369, 0.08025477707006369, 0.2832927409413515]
[0.954140127388535, 0.95, 0.9595959595959596, 0.9541311207198785, 0.045859872611464965, 0.045859872611464965, 0.2141491830744749]


In [202]:
import pandas as pd

df=pd.DataFrame({'MultinomialNB()':l1, 'Perceptron()':l2, 'RandomForestClassifier()':l3, 'LogisticRegression()':l4})

In [203]:
df.head()

MultinomialNB()  ...  LogisticRegression()
0         0.947771  ...              0.954140
1         0.911833  ...              0.950000
2         0.992424  ...              0.959596
3         0.947621  ...              0.954131
4         0.052229  ...              0.045860

[5 rows x 4 columns]

In [204]:
#function to determine best model

def model_eval(df):
  max=0
  max1=0
  for i in range(len(df.columns)):
    if(df.iloc[0,i]>max and df.iloc[3,i]>max1):
      max=df.iloc[0,i]
      max1=df.iloc[0,i]
      max_col=df.columns[i]
  return max_col

In [205]:
best_model=model_eval(df)

print(best_model)

LogisticRegression()
